### ISSUE TITLE
License this repository

### ISSUE THREAD

**Issue by liyishuai** [coq-community/templates#34]
Which license should we use, `LGPL-3.0-or-later`?

**Comment by Zimmi48** [comment]
Hum. This is a mistake from when the templates were split out of the manifesto repository. They were supposed to be under CC-0 license: https://github.com/coq-community/manifesto/blob/master/LICENSE.md

**Comment by liyishuai** [comment]
CC-0 seems more content-oriented and fits the manifesto. For the code here we could probably switch to an open source license.

**Comment by Zimmi48** [comment]
OK. Well, I am fine with any choice of open source license from the following list:
- Unlicense (public domain dedication, equivalent to CC-0)
- MIT (only requires attribution and preservation of license notices)
- MPL-2.0 (copyleft limited to file modification, not to inclusion in another project)

As long as it is understood that generating a file from a template is not the same as modifying a template and doesn't require to follow the license.

I am personally quite opposed to the use of LGPL in most new projects because this license is way too complex and hard to interpret in many situations. In particular, it creates strong requirements in situations where dynamic linking is not a technical option. IMHO people should prefer a choice between the weak copyleft of MPL-2.0 (easy to understand) and the strong copyleft of GPL-3.0 / AGPL-3.0 (relatively easy to understand as well, especially in the case of GPL). But strong copyleft seems a bit much for such a project.

**Comment by palmskog** [comment]
This was an incredibly quick open-close process for such a potentially far-reaching decision. I am strongly against any form of copyleft license, including LGPL and MPL. As substantial contributor I think more than a few hours of waiting for me to weigh in would be warranted.The one license I most prefer is MIT, but I'm also open to Unlicense or CC-0.

@liyishuai can you please roll back your commit that added `LICENSE` until we have something everybody agrees on?

**Comment by liyishuai** [comment]
Sorry for my negligence! I've dropped that commit.

**Comment by palmskog** [comment]
Thanks @liyishuai, I still appreciate that you raised the licensing issue. The main question seems to be whether we want to go near-public-domain or "regular permissive open source".

Here are some serious questions raised about CC-0, namely, that it has a very complicated fallback clause for jurisdictions that don't allow waiving all copyright: https://opensource.org/faq#cc-zero

So, as a first step, maybe we could say that we pick an unambiguous license that has a strong community? See the first category here: https://opensource.org/licenses/category

**Comment by Zimmi48** [comment]
The most known and commonly used permissive open source license today is MIT without doubt.

**Comment by palmskog** [comment]
Based on a discussion with @Zimmi48 on Coq's Zulip, the two of us have converged on recommending the [Unlicense](https://unlicense.org) as the most hassle-free license for template-related files, since it has been vetted for use with code and has good fallback where waiving copyright is not possible.

The main argument against a license like MIT is that we may have to insert a special clause to ensure that files generated through the templates **do not** fall under MIT but are owned by the user. With Unlicense, this is not a problem.

I am happy to license my contributions to the template repository under the Unlicense.

@Zimmi48 @liyishuai @erikmd @herbelin @amiloradovsky @anton-trunov as contributors to the templates repo, do you permit this code to be licensed under the Unlicense? Please give your response as a comment to this issue.

**Comment by liyishuai** [comment]
Approve Unlicense.

**Comment by Zimmi48** [comment]
Yes, I agree with the choice of Unlicense for this project (as already stated in your message), but let's be explicit :wink:

**Comment by anton-trunov** [comment]
I fully support Unlicense.

**Comment by erikmd** [comment]
Yes, I fully support Unilicense
