### ISSUE TITLE
Support using mathcomp images for CI

### ISSUE THREAD

**Issue by chdoc** [coq-community/templates#44]
Currently, the templates only support using the coq docker images for opam based CI. For projects depending on mathcomp this can be problematic/inconvenient for two reasons:

1. The full mathcomp takes quite a bit of time to build, so using images with mathcomp preinstalled would likely speed up CI runs.
2. The CI script always installs the latest version of mathcomp supported by the current package and the given version of Coq. For some projects it may be more relevant to test against multiple versions of mathcomp than to test many versions of Coq.

CC'in @erikmd , who is maintaining the mathcomp images and knows much better than me what would be the reasonable thing to do. 

(This is a follow-up to the following [Zulip discussion](https://coq.zulipchat.com/#narrow/stream/237977-Coq-users/topic/My.20first.20Coq.20opam.20package/near/198946982))

**Comment by erikmd** [comment]
Hi @chdoc, yes it is possible to address these two use cases just by specifying a custom Docker image tag, which incorporates a given version of coq and coq-mathcomp-character (both pinned in the image)

e.g. for the docker-coq-action, this is documented here:

https://github.com/coq-community/docker-coq-action#custom_image

and for the Travis CI and CircleCI templates, the docker image name can be modified directly.

but I agree that this kind of setting could be natively supported by the `meta.yml`, in order to customize it more easily.

E.g., by adding an optional YAML section in charge of **listing the desired versions of mathcomp?** (with the impediment that taking the naive product of {Coq versions} × {mathcomp versions} might not be as convenient as **listing the image tags themselves…**, see also that issue for a related discussion: https://github.com/coq-community/docker-coq-action/issues/7)

**Comment by Zimmi48** [comment]
Note the very similar issue #39 opened just a few hours before.

@erikmd IMHO the suggested YAML in #39 is all that's needed and would be much simpler to implement, while also being more generic.

**Comment by chdoc** [comment]
Sorry, I missed that issue, so I'm closing this one in favor of #39

**Comment by erikmd** [comment]
@Zimmi48 
> IMHO the suggested YAML in #39 is all that's needed and would be much simpler to implement, while also being more generic.

Yes I fully agree with you remark.
