### ISSUE TITLE
adding support for nighty and weekly builds for CI based on GitHub actions

### ISSUE THREAD

**Issue by chdoc** [coq-community/templates#77]
While converting some of my projects from Travis CI to GitHub actions, I realized that there is no easy (point and click) way to enable regular running of the CI on the master branch to catch up on changes to dependencies (in particular if CI runs against `coq.dev` or `mathcomp.dev`). 

I propose to introduce a new variable `cron_schedule` whose value is a cron schedule expression (e.g. `5 4 * * 1` for "At 04:05 on Monday", see [crontab.guru](https://crontab.guru/#5_4_*_*_1)) and implement this using [scheduled events](https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#scheduled-events).

Does someone already have a scheduled GitHub Action CI setup that we could adapt?

**Comment by Zimmi48** [comment]
We could also have a boolean variable to activate scheduled jobs and a default cron expression (e.g. `5 4 * * *`, i.e., every night) that you can override by providing another variable.

**Comment by chdoc** [comment]
While I do think that `coq-communty` is (presently) too small for this to truly matter, I would feel bad about encouraging a model where the bulk of all projects run their nightly/weekly CI the same minute. Unfortunately, our simple mustache-based setup does not allow us to randomize this. So it was a conscious decision to not suggest defaults. :thinking:

**Comment by erikmd** [comment]
Hi @chdoc, thanks for opening this issue!

> Does someone already have a scheduled GitHub Action CI setup that we could adapt?

here is an example: https://github.com/coq/bignums/blob/master/.github/workflows/build-coq-bignums.yml#L10-L12

> I would feel bad about encouraging a model where the bulk of all projects run their nightly/weekly CI the same minute

I fully agree with you remark.

but maybe a workaround for this issue would be just to hard-code a time slot of 1 hour, or 4 hours, e.g. 02:00/06:00 UTC (or make it configurable in the `meta.yml` file), then rely on the `generate` script to pick a random minute (or a multiple of 5 minutes) within the time slot… WDYT?

**Comment by chdoc** [comment]
@erikmd Thank you for the example, but I'm not entirely sure I fully understand the YAML structure of `schedule`. The documentation seems to suggest that `schedule` only ever applies to the latest commit on the default branch. Is that correct? 

> but maybe a workaround for this issue would be just to hard-code a time slot of 1 hour, or 4 hours, e.g. 02:00/06:00 UTC (or make it configurable in the `meta.yml` file), then rely on the `generate.sh` script to pick a random minute (or a multiple of 5 minutes) within the time slot… WDYT?

I don't like the idea of relying on the generate script for such things, because I fear that once we add one hack there, other hacks will follow. I think that generating a cron line (with the help of crontab.guru) is not too high a barrier for those who want scheduled builds. So I would simply put a link to this site in the `ref.yml` "documentation".

**Comment by erikmd** [comment]
> The documentation seems to suggest that `schedule` only ever applies to the latest commit on the default branch. Is that correct?

exactly: the scheduled workflows will only be run for the default branch

> I don't like the idea of relying on the generate script for such things, because
> I fear that once we add one hack there, other hacks will follow.

this is a nice proverb :)

however, if the feature at stake is properly implemented (so that it is not viewed as a hack!), I wouldn't be too afraid to extend that script.

> I think that generating a cron line (with the help of crontab.guru) is not too high a barrier for those who want scheduled builds. So I would simply put a link to this site in the `ref.yml` "documentation".

sure. but on the other hand, if there is no warning or so saying that the daily cron should be somewhat "random", users will probably always chose the same setting(?) and needing to further edit the generated file by hand makes the `generate.sh` feature handy (it is not automatic anymore)

anyway, it's true that my first proposal had drawbacks! in particular we would like that each `./generate.sh` run is deterministic… in particular, it should be idempotent!

So what would you think about the following idea, alternative to a mere documentation?

make as Théo proposed, a boolean `daily_cron: true`, and make the `./generate.sh` script takes an optional argument `--daily-cron HH:MM`:
  - if `daily_cron` holds **and** the optional arguments are not passed **and** no `cron` line already exist in the `coq-action.yml`, generate some random `HH` and `MM` and print an informative message saying that `daily_cron` was taken into account, and a schedule was generating as if `./generate-sh --daily-cron HH:MM` was run (thus making the customization of this setting discoverable);
  - if `daily_cron` holds and the `--daily-cron HH:MM` argument is passed, output:
    ```yaml
    schedule:
      # test master every day at 04:00 UTC
        - cron: '{{MM}} {{HH}} * * *'
    ```
  - if `daily_cron` holds **and** the optional arguments are not passed **and** the `coq-action.yml` file already contains that `cron` line, extract it and beforehand, so that `./generate.sh` is idempotent

WDYT?

**Comment by erikmd** [comment]
Hi @chdoc @Zimmi48, thoughts on my last proposal − https://github.com/coq-community/templates/issues/77#issuecomment-731805588 ?

**Comment by chdoc** [comment]
I still think that the simplest solution, to just ask people to define a `cron_schedule` variable in cron syntax is to be preferred. Moreover, I think the majority of projects will do just fine with a weekly schedule.

**Comment by Zimmi48** [comment]
@chdoc's solution being the easiest one to implement, I would just go with that one for now.
